<div id="container2">
    <aside class="aside-arena">	
        <div class="last-race-tienda"><!-- div contenedor cuadro1 -->
            <h4><img src="/imgs/notifi.png" class="centrarimg">Retos</h4>
            <ul id="retadores">
            </ul>
        </div>
        <div id="parte-verde-arena">
                <a href="#">Ver Todas</a>
        </div>
    </aside>
    <div id="linea-arena">
    </div>
    <section class="parte-central-arena">	
            <h1 class="alinear-h1"><img src="/imgs/rankin.png">Ranking de Jugadores</h1>
            <div class="cont-arena" id="ranking">
                    <table>
                        <thead>
                            <tr>
                                <td class="borde-radius1">Nombre</td>  
                                <td class="color">Posición</td>
                                <td class="color">Puntos</td>
                                <td class="borde-radius2">Conectado</td>
                            </tr>
                        </thead>
                    </table>
            </div>
    </section>
    <div id="linea-arena">
    </div>
    <aside class="aside2-arena">
            <div class="last-race-arena"><!-- div contenedor cuadro1 -->
                    <h4>Reta a un jugador</h4>
                    <img src="/imgs/cartas-arena-1.png">
                    <a class="bot-activar" href="#carta-reto-box" id="retar">
                            <div>
                                    <h5 style="text-align: center">Retar &nbsp;</h5>
                            </div>
                    </a>
            </div>
            <br/>
    </aside>
    <div id="linea-h">
    </div>
    
</div>
<div style="display:none">
    <div id="carta-reto-box" class="modal">
        <h2>Retar a un jugador</h2>
        <hr/>
        <p>Escriba el nombre del jugador que desea retar:</p>
        <input type="text" value="" name="jugador" id="jugador">
        <div id="jugadores">
           <table>                   
           </table>
        </div>
        <div id="apuesta">
            <p>Puntos apostados:</p>
            <input type="text" value="" name="apuesta" id="apuesta">
        </div>
        <hr/>
        <input type="button" value="Enviar Reto" id="enviarreto"/>
        <input type="button" value="Cancelar"/>
    </div>
</div>
<div style="display:none">
    <div id="reto-box" class="modal">
        <div id="clock"></div>
        <div style="width: 95%">
            <div id="reto-title">
            <h2>Reto con %jugador%</h2>
            <hr/>
            </div>
            <div class="pregunta">
                <ul class="controles">
                    <li>
                        <select>
                            <option>Seleccione una carta...</option>
                        </select>
                        <input type="button" value="Usar carta"/>
                    </li>
                </ul>
                <img src="/imgs/logan.jpg" width="480">
                <p>Era lunes por la mañana... faltaba una semana para que empezara el festival
                pero la escuela aun seguía envuelta en una atmósfera bastante relajada.
                ¿Realmente planea este instituto celebrar un festival escolar? ¿No debería
                estar un poco más animado?
                </p>
                <ul class="respuestas" id="respuesta">
                    <li><input type="button" class="btn" value="Respuesta 1"></li>
                    <li><input type="button" class="btn" value="Respuesta 1"></li>
                    <li><input type="button" class="btn" value="Respuesta 1"></li>
                    <li><input type="button" class="btn" value="Respuesta 1"></li>
                </ul>
            </div>
        </div>
    </div>
</div>