<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <title>VaGanar.com :: Panel de Administración</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="<?= $this->baseUrl() ?>/adm/css/bootstrap.css" rel="stylesheet">
    <link href="<?= $this->baseUrl() ?>/adm/css/admin.css" rel="stylesheet">
    <link href="<?= $this->baseUrl() ?>/adm/css/bootstrap-responsive.css" rel="stylesheet">
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="<?= $this->baseUrl() ?>/adm/images/favicon.ico">

    <link rel="apple-touch-icon" href="<?= $this->baseUrl() ?>/adm/images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="<?= $this->baseUrl() ?>/adm/images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="<?= $this->baseUrl() ?>/adm/images/apple-touch-icon-114x114.png">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of 
        the topbar */
      }
      /* mi estilo */

    </style>

    

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Panel de Administración de VaGanar.com</a>
          
        </div>
      </div>

    </div>

    <div class="container">
        <div class="row">
            <div class="span3">
                    <ul class="nav nav-pills nav-stacked">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="/admin/Prueba">Pruebas</a></li>
                        <li><a href="/admin/Patrocinador">Patrocinadores</a></li>
                        <li><a href="/admin/Carrera">Carreras</a></li>
                        <li><a href="#">Home</a></li>
                    </ul>
            </div>
            <div class="span9">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
                   
    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <?= $this->headScript() ?>
  </body>
</html>
