<div id="container2">
    <aside>
        <div class="cont-index-izquierda">
            <div>
                <h2>Titulo</h2>
            </div>
            <ul class="lista-index">
                <li><a href="#">Item One</a></li>
                <li><a href="#">Item Two</a></li>
		<li><a href="#">Item Three</a></li>
            </ul>
         </div>
    </aside>
    <div id="linea">
    </div>
    <section class="parte-central-index">
        <!--<div class="contenido-prnc-index">
        </div>-->
        <div class="slogan-style">
            <h2>Entra, Juega, Socializa y siempre ganas</h2>
        </div>
        <div class="cont-slide">
            <img src="imgs/logo-slide.png">
        </div>
        <div class="slogan-style2">
            <h2>Registrate es gratis!</h2>
        </div>
    </section>
    <div id="linea">
    </div>
    <aside>
        <div class="last-race-index">
            <ul class="lista-index-derecha">
		<li><a href="#">Guia para principiantes</a></li>
		<li><a href="#">Preguntas frecuentes</a></li>
		<li><a href="#">Item One</a></li>
		<li><a href="#">Item Two</a></li>
                <li><a href="#">Item Three</a></li>
            </ul>
	</div>
	<div id="linea-h-index">
	</div>
	<div class="last-race-index2">
            <ul class="lista-index-derecha">
		<li><a href="#">Item One</a></li>
		<li><a href="#">Item Two</a></li>
		<li><a href="#">Item Three</a></li>
            </ul>
	</div>
    </aside>
</div>