<div id="container">
    <aside>
        <div class="last-race"><!-- div contenedor cuadro1 -->
            <h4><img src="imgs/cartas.png" class="centrarimg">Mis Cartas</h4>
            <ul id="ul-main-comprar">
                <li>
                    <span>
                        <div class="label-comprar">Carta de Reto:</div>
                        <a href="#">2</a>
                    </span>
                </li>
                <li>
                    <span>
                        <div class="label-comprar">Carta de Bloqueo:</div>
                        <a href="#">0</a>
                    </span>
                </li>
                <li>
                    <span>
                        <div class="label-comprar">C. Llave Maestra:</div>
                        <a href="#">0</a>
                    </span>
                </li>
            </ul>
            <a class="more-2" href="#">Ver más</a>
        </div>
    </aside>
			<div id="linea">
			</div>
    <section>
        <div class="table-cell">
            <div class="historys">
                <header><h4>Descripción Carta</h4></header><!-- encabezado cuadro1 -->
                <div class="tabla"><!-- div display table -->
                    <div class="padding-no"><!-- table cell 1 cuadro 1 -->
                            <img src="imgs/carta1-2.png"><!-- imagen de la prueba -->
                            <a href="#"><h4 class="centrar-precio">320b</h4></a>
                    </div>
                    <div class="cell2"><!-- table cell 2 cuadro 1 -->
                        <div><!-- div contenedor del article -->
                            <article>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's.</article>
                            <a class="bot-comprar" href="#">
                                    <div>
                                            <h5>Comprar</h5>
                                    </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div><!-- div contenedor cuadro1 -->
            <div class="historys"><!-- div contenedor cuadro2 -->
                <header><h4>Descripción Carta</h4></header><!-- encabezado cuadro2 -->
                <div class="tabla"><!-- div display table -->
                    <div class="padding-no"><!-- table cell 1 cuadro 2 -->
                        <img src="imgs/carta2-2.png"><!-- imagen de la prueba -->
                        <a href="#"><h4 class="centrar-precio">330b</h4></a>
                    </div>
                    <div class="cell2"><!-- table cell 2 cuadro 2 -->
                        <div><!-- div contenedor del article -->
                            <article>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's.</article>
                            <a class="bot-comprar" href="#">
                                <div>
                                    <h5>Comprar</h5>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- table cell1 -->
        <div class="table-cell">
            <div class="historys">
                <header><h4>Descripción Carta</h4></header><!-- encabezado cuadro3 -->
                <div class="tabla"><!-- div display table -->
                    <div class="padding-no"><!-- table cell 1 cuadro 3 -->
                        <img src="imgs/carta3-2.png"><!-- imagen de la prueba -->
                        <a href="#"><h4 class="centrar-precio">270b</h4></a>
                    </div>
                    <div class="cell2"><!-- table cell 2 cuadro 3 -->
                        <div><!-- div contenedor del article -->
                            <article>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's.</article>
                            <a class="bot-comprar" href="#">
                                <div>
                                   <h5>Comprar</h5>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div><!-- div contenedor cuadro3 -->
            <div class="historys">
                <header><h4>Descripción Carta</h4></header><!-- encabezado cuadro4 -->
                <div class="tabla"><!-- div display table -->
                    <div class="padding-no"><!-- table cell 1 cuadro 4 -->
                        <img src="imgs/carta4-2.png"><!-- imagen de la prueba -->
                        <a href="#"><h4 class="centrar-precio">400b</h4></a>
                    </div>
                    <div class="cell2"><!-- table cell 2 cuadro 4 -->
                        <div><!-- div contenedor del article -->
                            <article>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's.</article>
                            <a class="bot-comprar" href="#">
                                <div>
                                    <h5>Comprar</h5>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div><!-- div contenedor cuadro4 -->
        </div><!-- table cell2 -->
    </section>
    <div>
        <a id="pagina-siguiente" href="#">Siguiente Pagina</a>
    </div>
</div>