<div class="row">
    <div class="span15">
        <div id="inner-logo">
            <h2 class="aaaight">VaGanar.com</h2>
        </div> 
   </div>
</div>

<div class="capa1">
     <div class="row">
         <div id="inner-action-name">
            <h2 class="aaaight">Pruebas de la Carrera</h2>
         </div>
        <div class="span14">
            <a class="btn btn-large btn-success ptsansbold" style="text-align: center">
                <i class="icon-list icon-white"></i> Carreras vigentes
            </a>
            <div id="module-estadisticas-carrera">
                <p class="titulo ptsansbold">Carrera Actual</p>
                <table class="ptsansregular">
                    <tr>
                        <td>Completado</td>
                        <td>0%</td>
                    </tr>
                    <tr>
                        <td>Puntos</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>Posición</td>
                        <td>0</td>
                    </tr>
                </table>
                <a style="text-align: center; margin-top: 6px;" href="#"><p class="ptsansbold">Ver Estadísticas</p></a>
            </div>
        </div>
        <div class="span13" id="inner-pruebas">
            <div class="capa2" id="pruebas">
                <div class="prueba-item">
                    <h3><span style="color: #bbb">#1 </span>¿Qué cantante famoso de rap ganó un Premio...</h3>
                    <p style="color: #888;font-style:italic;text-align: right">100 puntos - Patrocina: Bavaria</p>
                </div>
                <div class="prueba-item">
                    <h3><span style="color: #bbb">#2 </span>¿Qué cantante famoso de rap ganó un Premio...</h3>
                    <p style="color: #888;font-style:italic;text-align: right">100 puntos - Patrocina: Bavaria</p>
                </div>
                <div class="prueba-item">
                    <h3><span style="color: #bbb">#3 </span>¿Qué cantante famoso de rap ganó un Premio...</h3>
                    <p style="color: #888;font-style:italic;text-align: right">100 puntos - Patrocina: Bavaria</p>
                </div>
                <div class="prueba-item">
                    <h3><span style="color: #bbb">#4 </span>¿Qué cantante famoso de rap ganó un Premio...</h3>
                    <p style="color: #888;font-style:italic;text-align: right">100 puntos - Patrocina: Bavaria</p>
                </div>
                <div class="prueba-item">
                    <h3><span style="color: #bbb">#5 </span>¿Qué cantante famoso de rap ganó un Premio...</h3>
                    <p style="color: #888;font-style:italic;text-align: right">100 puntos - Patrocina: Bavaria</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="navigation">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#" >Carrera</a></li>
        <li><a href="#">Retos</a></li>
        <li><a href="#">Tienda</a></li>
        <li><a href="#">Perfil</a></li> 
    </ul>
</div>
