<div id="container">
    <aside>
        <div class="last-race"><!-- div contenedor cuadro1 -->
        <h4><img src="/imgs/estadisticas_as.png" class="centrarimg">Carrera Actual</h4>
            <ul id="ul-main" role="carrera">
                <li id="progreso">
                    <span>
                            <div class="label">% Completado</div>
                            <a href="#">0%</a>
                    </span>
                </li>
                <li id="puntos">
                    <span>
                            <div class="label">Ptos. Jugador</div>
                            <a href="#">0</a>
                    </span>
                </li>
                <li>
                    <span>
                            <div class="label">Pos. Jugador</div>
                            <a href="#">1</a>
                    </span>
                </li>
                <li id="pruebas">
                    <span>
                            <div class="label">Pruebas</div>
                            <a href="#">0</a>
                    </span>
                </li>
            </ul>
            <a class="more" href="#">Ver Estadistica Completa</a>
        </div>
        <div class="last-race"><!-- div contenedor cuadro2 -->
            <h4><img src="/imgs/estadisticas_as.png" class="centrarimg">Acumulado</h4>
            <ul id="ul-main">
                <li>
                    <span>
                            <div class="label">Ranking Individual</div>
                            <a href="#">58%</a>
                    </span>
                </li>
                <li>
                    <span>
                            <div class="label">Ptos. Acumulados</div>
                            <a href="#">1600</a>
                    </span>
                </li>
                <li>
                    <span>
                            <div class="label">Tot. Pruebas</div>
                            <a href="#">36</a>
                    </span>
                </li>
                <li>
                    <span>
                            <div class="label">Monedas</div>
                            <a href="#">85</a>
                    </span>
                </li>
            </ul>
            <a class="more" href="#">Ver Estadistica Completa</a>
        </div>
        </aside>
        <div id="linea">
        </div>
        <section id="historias">   
        </section>
        <div>
                <a id="pagina-siguiente" href="#">Siguiente Pagina</a>
        </div>
</div>

