<div id="container2">
    <aside class="aside-arena">	
        <div class="last-race-tienda"><!-- div contenedor cuadro1 -->
            <h4><img src="imgs/notifi.png" class="centrarimg">Notificaciones</h4>
            <ul id="ul-main-arena">
                    <li>
                            <a href="#">Fabio14 te ha retado</a>
                    </li>
                    <li>
                            <a href="#">Tu carta de bloqueo expira hoy</a>	
                    </li>
                    <li>
                            <a href="#">Ramongr quiere ser tu aliado</a>	
                    </li>
            </ul>
        </div>
        <div id="parte-verde-arena">
                <a href="#">Ver Todas</a>
        </div>
    </aside>
    <div id="linea-arena">
    </div>
    <section class="parte-central-arena">	
            <h1 class="alinear-h1"><img src="imgs/rankin.png">Ranking de Jugadores</h1>
            <div class="cont-arena" id="ranking">
                    <table>
                        <thead>
                            <tr>
                                <td class="borde-radius1">Nombre</td>                                            </td><td class="color">Post
                                <td class="color">Cartas</td>
                                <td class="color">Puntos</td>
                                <td class="borde-radius2">Employee</td>
                            </tr>
                        </thead>

                    </table>
            </div>
            <input class="caja-buscar" name="caja-buscar" type="text">
            <input class="caja-buscar" name="caja-buscar" type="text">
            <div class="cont-bot-buscar">
                    <a class="bot-buscar" href="#">
                            <div>
                                    <h5>buscar</h5>
                            </div>
                    </a>
            </div>
    </section>
    <div id="linea-arena">
    </div>
    <aside class="aside2-arena">
            <div class="last-race-arena"><!-- div contenedor cuadro1 -->
                    <h4>Activa una Carta</h4>
                    <img src="imgs/cartas-arena-3.png">
                    <a class="bot-activar" href="#">
                            <div>
                                    <h5>Activar</h5>
                            </div>
                    </a>
            </div>
    </aside>
    <div id="linea-h">
    </div>
    <section class="section-abajo">
            <div>
                    <h2 class="centrar-miscartas"><img src="imgs/icono-cartas.png" class="centrarimg">Mis Cartas</h2>
            </div>
            <div id="base-cartas">
                    <a href="#carta-reto-box" id="retar"><img class="centrar-naipe" src="imgs/cartas-arena-1.png"></a>
                    <img class="centrar-naipe" src="imgs/cartas-arena-2.png">
                    <img class="centrar-naipe" src="imgs/cartas-arena-3.png">
                    <img class="centrar-naipe" src="imgs/cartas-arena-4.png">
                    <img class="centrar-naipe" src="imgs/cartas-arena-2.png">
            </div>
    </section>
</div>
<div style="display:none">
    <div id="carta-reto-box" class="modal">
        <h2>Retar a un jugador</h2>
        <hr/>
        <p>Escriba el nombre del jugador que desea retar:</p>
        <input type="text" value="" name="jugador" id="jugador">
        <div id="jugadores">
           <table>                   
           </table>
        </div>
        <div id="apuesta">
            <p>Puntos apostados:</p>
            <input type="text" value="" name="apuesta" id="apuesta">
        </div>
        <hr/>
        <input type="button" value="Enviar Reto"/>
        <input type="button" value="Cancelar"/>
    </div>
</div>