<div id="container2">
    <aside class="aside-arena">	
        <div class="last-race-tienda"><!-- div contenedor cuadro1 -->
            <h4><img src="imgs/notifi.png" class="centrarimg">Notificaciones</h4>
            <ul id="ul-main-arena">
            </ul>
        </div>
        <div id="parte-verde-arena">
                <a href="#">Ver Todas</a>
        </div>
    </aside>
    <div id="linea-arena">
    </div>
    <section class="parte-central-arena">	
            <h1 class="alinear-h1"><img src="imgs/rankin.png">Ranking de Jugadores</h1>
            <div class="cont-arena" id="ranking">
                    <table>
                        <thead>
                            <tr>
                                <td class="borde-radius1">Nombre</td>  
                                <td class="color">Posición</td>
                                <td class="color">Cartas</td>
                                <td class="color">Puntos</td>
                                <td class="borde-radius2">Conectado</td>
                            </tr>
                        </thead>
                    </table>
            </div>
    </section>
    <div id="linea-arena">
    </div>
    <aside class="aside2-arena">
            <div class="last-race-arena"><!-- div contenedor cuadro1 -->
                    <h4>Reta a un jugador</h4>
                    <img src="imgs/cartas-arena-1.png">
                    <a class="bot-activar" href="#carta-reto-box" id="retar">
                            <div>
                                    <h5 style="text-align: center">Retar &nbsp;</h5>
                            </div>
                    </a>
            </div>
    </aside>
    <div id="linea-h">
    </div>
    
</div>
<div style="display:none">
    <div id="carta-reto-box" class="modal">
        <h2>Retar a un jugador</h2>
        <hr/>
        <p>Escriba el nombre del jugador que desea retar:</p>
        <input type="text" value="" name="jugador" id="jugador">
        <div id="jugadores">
           <table>                   
           </table>
        </div>
        <div id="apuesta">
            <p>Puntos apostados:</p>
            <input type="text" value="" name="apuesta" id="apuesta">
        </div>
        <hr/>
        <input type="button" value="Enviar Reto"/>
        <input type="button" value="Cancelar"/>
    </div>
</div>