<div id="container2">
    <aside class="aside-arena">	
        <div class="last-race-tienda"><!-- div contenedor cuadro1 -->
            <h4><img src="imgs/notifi.png" class="centrarimg">Notificaciones</h4>
            <ul id="ul-main-arena">
                    <li>
                            <a href="#">Fabio14 te ha retado</a>
                    </li>
                    <li>
                            <a href="#">Tu carta de bloqueo expira hoy</a>	
                    </li>
                    <li>
                            <a href="#">Ramongr quiere ser tu aliado</a>	
                    </li>
            </ul>
        </div>
        <div id="parte-verde-arena">
                <a href="#">Ver Todas</a>
        </div>
    </aside>
    <div id="linea-arena">
    </div>
    <section class="parte-central-arena">	
            <h1 class="alinear-h1"><img src="imgs/rankin.png">Ranking de Jugadores</h1>
            <div class="cont-arena">
                    <table>
                        <thead>
                            <tr>
                                <td class="borde-radius1">Nombre</td>                                            </td><td class="color">Post
                                <td class="color">Cartas</td>
                                <td class="color">Puntos</td>
                                <td class="borde-radius2">Employee</td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Giacomo Guilizzoni Founder &amp; CEO</td>
                                <td class="alinear">1</td>
                                <td class="alinear"><a href="#">Ver Cartas</a></td>
                                <td class="alinear">5300</td>
                                <td class="centrar"><img src="imgs/check.png"></td>
                            </tr>
                            <tr>
                                <td>Guido Jack Guilizzoni</td>
                                <td class="alinear">2</td>
                                <td class="alinear"><a href="#">Ver Cartas</a></td>
                                <td class="alinear">5233</td>
                                <td class="centrar"><img src="imgs/check.png"></td>
                            </tr>
                            <tr>	
                                <td>Marco Buttom Tuttofare</td>
                                <td class="alinear">3</td>
                                <td class="alinear"><a href="#">Ver Cartas</a></td>
                                <td class="alinear">5122</td>
                                <td class="centrar"><img src="imgs/check.png"></td>
                            </tr>
                            <tr>
                                <td>Mariah Maclachlan Better Half</td>
                                <td class="alinear">3</td>
                                <td class="alinear"><a href="#">Ver Cartas</a></td>
                                <td class="alinear">5122</td>
                                <td class="centrar"><img src="imgs/check.png"></td>
                            </tr>
                            <tr>
                                <td>Valerie Liberty COO WOW! Division</td>
                                <td class="alinear">4</td>
                                <td class="alinear"><a href="#">Ver Cartas</a></td>
                                <td class="alinear">5060</td>
                                <td class="centrar"><img src="imgs/check.png"></td>
                            </tr>
                        </tbody>
                    </table>
            </div>
            <input class="caja-buscar" name="caja-buscar" type="text">
            <input class="caja-buscar" name="caja-buscar" type="text">
            <div class="cont-bot-buscar">
                    <a class="bot-buscar" href="#">
                            <div>
                                    <h5>buscar</h5>
                            </div>
                    </a>
            </div>
    </section>
    <div id="linea-arena">
    </div>
    <aside class="aside2-arena">
            <div class="last-race-arena"><!-- div contenedor cuadro1 -->
                    <h4>Activa una Carta</h4>
                    <img src="imgs/cartas-arena-3.png">
                    <a class="bot-activar" href="#">
                            <div>
                                    <h5>Activar</h5>
                            </div>
                    </a>
            </div>
    </aside>
    <div id="linea-h">
    </div>
    <section class="section-abajo">
            <div>
                    <h2 class="centrar-miscartas"><img src="imgs/icono-cartas.png" class="centrarimg">Mis Cartas</h2>
            </div>
            <div id="base-cartas">

                    <img class="centrar-naipe" src="imgs/cartas-arena-1.png">
                    <img class="centrar-naipe" src="imgs/cartas-arena-2.png">
                    <img class="centrar-naipe" src="imgs/cartas-arena-3.png">
                    <img class="centrar-naipe" src="imgs/cartas-arena-4.png">
                    <img class="centrar-naipe" src="imgs/cartas-arena-2.png">

            </div>
    </section>
</div>