<div id="container2">
    <aside>
        <div class="last-race-tienda"><!-- div contenedor cuadro1 -->
            <h4><img src="/imgs/articulos.png" class="centrarimg">Mis Articulos</h4>
            <ul id="ul-main">
                    <li>
                            <span>
                                    <div class="label">Carrito de Compras</div>
                                    <a href="#">3</a>
                            </span>
                    </li>
                    <li>
                            <span>
                                    <div class="label"><a href="#">Favoritos</a></div>
                                    <a href="#">0</a>
                            </span>
                    </li>
            </ul>
            <a id="more" href="#"><h4><img src="/imgs/monedas.png" class="centrarimg">Mis Monedas</h4></a>
        </div>
        <div id="parte-verde">
            <a href="#">5300b</a>
        </div>
        </aside>
        <div id="linea">
        </div>
        <section>
        <div class="container1"><!--                          div cell1                   -->
            <div class="cont-estruct"><!-- div contenedor estructura 1 -->
                    <img class="img-centrar" src="/imgs/img-producto.png"><!-- imagen producto -->
                    <div class="nombre-producto"><!-- div nombre producto1 -->
                            <a class="nom-producto" href="#"><strong>Nombre del Producto</strong></a>
                    </div>
                    <div class="precio-producto"><!-- div precio producto1 -->
                            <h5 class="precio-centrar">5000b</h5>
                    </div>
            </div>
            <div class="cont-estruct"><!-- div contenedor estructura 2 -->
                    <img class="img-centrar" src="/imgs/img-producto.png"><!-- imagen producto -->
                    <div class="nombre-producto"><!-- div nombre producto2 -->
                            <a class="nom-producto" href="#"><strong>Nombre del Producto</strong></a>
                    </div>
                    <div class="precio-producto"><!-- div precio producto2 -->
                            <h5 class="precio-centrar">4500b</h5>
                    </div>
            </div>
        </div>
        <div class="container1"><!--                           div cell2                    -->
            <div class="cont-estruct"><!-- div contenedor estructura 3 -->
                    <img class="img-centrar" src="/imgs/img-producto.png"><!-- imagen producto -->
                    <div class="nombre-producto"><!-- div nombre producto3 -->
                            <a class="nom-producto" href="#"><strong>Nombre del Producto</strong></a>
                    </div>
                    <div class="precio-producto"><!-- div precio producto3 -->
                            <h5 class="precio-centrar">8500b</h5>
                    </div>
            </div>
            <div class="cont-estruct"><!-- div contenedor estructura 4 -->
                    <img class="img-centrar" src="/imgs/img-producto.png"><!-- imagen producto -->
                    <div class="nombre-producto"><!-- div nombre producto4 -->
                            <a class="nom-producto" href="#"><strong>Nombre del Producto</strong></a>
                    </div>
                    <div class="precio-producto"><!-- div precio producto4 -->
                            <h5 class="precio-centrar">7800b</h5>
                    </div>
            </div>
        </div>
        <div class="container1"><!--                            div cell3                   -->
            <div class="cont-estruct"><!-- div contenedor estructura 5 -->
                    <img class="img-centrar" src="/imgs/img-producto.png"><!-- imagen producto -->
                    <div class="nombre-producto"><!-- div nombre producto5 -->
                            <a class="nom-producto" href="#"><strong>Nombre del Producto</strong></a>
                    </div>
                    <div class="precio-producto"><!-- div precio producto5 -->
                            <h5 class="precio-centrar">5200b</h5>
                    </div>
            </div>
            <div class="cont-estruct"><!-- div contenedor estructura 6 -->
                    <img class="img-centrar" src="/imgs/img-producto.png"><!-- imagen producto -->
                    <div class="nombre-producto"><!-- div nombre producto6 -->
                            <a class="nom-producto" href="#"><strong>Nombre del Producto</strong></a>
                    </div>
                    <div class="precio-producto"><!-- div precio producto6 -->
                            <h5 class="precio-centrar">5000b</h5>
                    </div>
            </div>
        </div>
    </section>
</div>